name: Robot Framework CI

on:
  push:
    branches: [ main, develop ]  # Dispara ao fazer push nestas branches
  pull_request:
    branches: [ main ]          # Dispara em PRs para a branch main

jobs:
  test:
    runs-on: ubuntu-latest       # Sistema operacional da máquina virtual

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Baixa o código do repositório

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   # Versão do Python

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary  # Se usar Selenium
          # Outras bibliotecas (ex: requests, Appium, etc.)

      - name: Run Robot Framework tests
        run: robot --outputdir results tests/  # Executa testes na pasta 'tests/'

      - name: Upload results (opcional)
        uses: actions/upload-artifact@v3
        if: always()  # Faz upload mesmo se os testes falharem
        with:
          name: robot-reports
          path: results/  # Pasta com os relatórios (outputdir)